---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# punkapi

<!-- badges: start -->
<!-- badges: end -->

## About

A collaboratively built package created during a [package development training](https://thinkr.fr/formation-au-logiciel-r/creation-de-packages-r/).

The `{punkapi}` package will contain functions to call the Punk API. 
Documentation is at: https://punkapi.com/documentation/v2

## How to

The list of tasks are at https://github.com/ThinkR-open/punkapi/issues

These issues contain a series of functions to implement and bugs to fix. 

Step by step:

1. Clone this repo to your computer
1. Leave a comment on one issue to indicate you want to work on it
1. Create a new branch, starting from `dev`, named `issue-XXX`, where `XXX` is the issue you want to work on
1. Once you've done the implementation, make sure your branch is up-to-date with `dev`
1. Make a PR to `dev`
1. Your branch should pass the GitHub Action check to be valid
1. Tag @colinfay as a reviewer
1. Work on another issue

## Requirements

1. Every function should check the user inputs
1. Every function should fail gracefully (i.e return an informative messages in case of failure)
1. Every function should be fully documented
1. Every dependency should be fully set 

